services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres_container
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      POSTGRES_PASSWORD: mySecretPassword
      POSTGRES_USER: iyanuoluwa
      POSTGRES_DB: ratelimitr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ratelimitr-network

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - ratelimitr-network

networks:
  ratelimitr-network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
